### ISSUE TITLE
status=0 in the linkcheckerrc has no effect

### ISSUE THREAD

**Issue by mistyhacks** [linkchecker/linkchecker#52]
If I pass `--no-status` when starting the linkchecker, the status is not logged. However, if I have `status=0` in the `[output]` section of the `linkcheckerrc` file, it has no effect and the status messages are still printed. Other things in the file are being honored.

**Comment by thezoggy** [comment]
I can confirm this is still outstanding in latest code from git. Also I tried `status=False` with `status=0` with no change. Only `--no-status` worked.

**Comment by cjmayo** [comment]
> I can confirm this is still outstanding in latest code from git. Also I tried `status=False` with `status=0` with no change. Only `--no-status` worked.

Thanks for checking with git.

> also to note, missing what 'default' is with help
> https://github.com/linkchecker/linkchecker/blob/master/linkchecker#L342

True that it isn't consistent, but I think this is one of the correct ones - as an argument with no value, by definition it is changing the default.

Hopefully I have fixed this with #471. If you have an opportunity to test do comment there.

**Comment by thezoggy** [comment]
Just updated to latest 
```
% pip3 install --upgrade git+https://github.com/linkchecker/linkchecker.git
Collecting git+https://github.com/linkchecker/linkchecker.git
  Cloning https://github.com/linkchecker/linkchecker.git to /tmp/pip-req-build-qv20v2kf
  Running command git clone -q https://github.com/linkchecker/linkchecker.git /tmp/pip-req-build-qv20v2kf
Requirement already satisfied, skipping upgrade: requests>=2.4 in ./lib/python3.6/site-packages (from LinkChecker==10.0.0.dev0) (2.24.0)
Requirement already satisfied, skipping upgrade: dnspython in ./lib/python3.6/site-packages (from LinkChecker==10.0.0.dev0) (1.16.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in ./lib/python3.6/site-packages (from LinkChecker==10.0.0.dev0) (4.9.1)
Requirement already satisfied, skipping upgrade: pyxdg in ./lib/python3.6/site-packages (from LinkChecker==10.0.0.dev0) (0.26)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in ./lib/python3.6/site-packages (from requests>=2.4->LinkChecker==10.0.0.dev0) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.6/site-packages (from requests>=2.4->LinkChecker==10.0.0.dev0) (1.25.9)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./lib/python3.6/site-packages (from requests>=2.4->LinkChecker==10.0.0.dev0) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in ./lib/python3.6/site-packages (from requests>=2.4->LinkChecker==10.0.0.dev0) (2.10)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in ./lib/python3.6/site-packages (from beautifulsoup4->LinkChecker==10.0.0.dev0) (2.0.1)
Using legacy setup.py install for LinkChecker, since package 'wheel' is not installed.
Installing collected packages: LinkChecker
  Attempting uninstall: LinkChecker
    Found existing installation: LinkChecker 10.0.0.dev0
    Uninstalling LinkChecker-10.0.0.dev0:
      Successfully uninstalled LinkChecker-10.0.0.dev0
    Running setup.py install for LinkChecker ... done
Successfully installed LinkChecker-10.0.0.dev0
```

testing again, no change.
still seeing the status with `status=0` or `status=False` :(

```
% linkchecker --config=linkcheckerrc https://assets.ubuntu.com/v1/72dcc529-containers-illustration_AW.svg https://assets.ubuntu.com/v1/450d7c2f-openstack-hero.svg
LinkChecker 10.0.0.dev0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2020-08-10 17:29:06+000

URL        `https://assets.ubuntu.com/v1/72dcc529-containers-illustration_AW.svg'
Real URL   https://assets.ubuntu.com/v1/72dcc529-containers-illustration_AW.svg
Check time 0.767 seconds
Result     Valid: 200 OK
 1 thread active,     0 links queued,    1 link in   2 URLs checked, runtime 1 seconds

URL        `https://assets.ubuntu.com/v1/450d7c2f-openstack-hero.svg'
Real URL   https://assets.ubuntu.com/v1/450d7c2f-openstack-hero.svg
Check time 2.194 seconds
Result     Valid: 200 OK

Statistics:
Downloaded: 0B.
Content types: 2 image, 0 text, 0 video, 0 audio, 0 application, 0 mail and 0 other.
URL lengths: min=56, max=68, avg=62.

That's it. 2 links in 2 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2020-08-10 17:29:09+000 (3 seconds)
```

**Comment by cjmayo** [comment]
The PR isn't merged yet! (merging should automatically close this issue).

**Comment by thezoggy** [comment]
ha my bad, i saw the notification on my phone to re-test and failed to see it didnt get merged yet, will re-check after the fact
